### ISSUE TITLE
ClearVolume network protocol: data type string change

### ISSUE THREAD

**Issue by royerloic** [ClearVolume/ClearVolume#10]
The 'type' field has changed. Possible types are:
        Byte,
	UnsignedByte,
	Short,
	UnsignedShort,
	Int,
	UnsignedInt,
	Long,
	UnsignedLong,
	HalfFloat,
	Float,
	Double,

Only UnsignedByte and UnsignedShort are supported right now.

**Comment by skalarproduktraum** [comment]
@maweigert @royerloic Is this still something current or can I close this? The issue text is also not exactly descriptive :-D

**Comment by maweigert** [comment]
Afaik can be closed. Unless @royerloic wants to elaborate ;)

**Comment by skalarproduktraum** [comment]
I guess this is also related to #17, so I'm closing this.
