### ISSUE TITLE
Multi-pass rendering affects quality of recorded movies

### ISSUE THREAD

**Issue by HannahBa** [ClearVolume/ClearVolume#12]
An option for deactivating it when recording rotations would be useful.

**Comment by royerloic** [comment]
Added a key binding for toggling on/off the multi-pass rendering: CTRL+M
As soon as the changes are propagated downstream you will be able to deactivate
the multipass for better quality rendering. Also, there will be soon (today?!) better key bindings for controlling the rotation and translation with keys as well as auto rotation...
