### ISSUE TITLE
VoxelSizeZ ignored bluntly!

### ISSUE THREAD

**Issue by fjug** [ClearVolume/ClearVolume#18]
Other voxel sizes might also not work, but for Z I confirm by:

cv.setVolumeDataBuffer(
					c,
					ByteBuffer.wrap( bytes ),
					sizeX,
					sizeY,
					sizeZ,
					voxelSizeX,
					voxelSizeY,
					voxelSizeZ );
			System.out.println( ">>>>> " + voxelSizeZ );

Sysout shows e.g. 2.0 all the time, but shown volume gets super flat.

**Comment by royerloic** [comment]
fixed
