### ISSUE TITLE
Fiji plugin does not show modified image

### ISSUE THREAD

**Issue by CBlasse** [ClearVolume/ClearVolume#20]
Reproduce like this:
 - open image
 - show in CV
 - close CV
 - crop or convolute image etc.
 - open in CV
 - shown data will be like the original, not the modified image

**Comment by royerloic** [comment]
Thanks, We have still a refresh issue within Fiji, this needs a fix asap indeed...
The workaround for now is to go into full screem mode by double clicking on the display and then coming back (ESC or again double click).

**Comment by fjug** [comment]
I fixed this problem in the past already... sorry for not closing this issue earlier.
