### ISSUE TITLE
Timepoint support in Fiji plugin

### ISSUE THREAD

**Issue by skalarproduktraum** [ClearVolume/ClearVolume#28]
The Fiji plugin currently only supports single timepoints. This could be addressed in a manner similar to the demo application or the OpenSPIM plugin.

**Comment by royerloic** [comment]
It should work. Florian implemented it. Could you put the problematic Tiff folder into a temp folder in DropBox ?

**Comment by skalarproduktraum** [comment]
Oups. I just missed it, sorry! Closing
