### ISSUE TITLE
Install labview version

### ISSUE THREAD

**Issue by cloudsforest** [ClearVolume/ClearVolume#31]
Hi there,

I tried to install labview version in my 64 bit computer with labview 2013 64 bit version. But it shows a error message of "Sorry, but due to the large data handled, ClearVolume only supports 64 bit architectures."

Could you kindly look into this issue please?

Chen Qian
the Francis Crick Institute, London, UK

**Comment by skalarproduktraum** [comment]
Hello Chen,

the reason could be that - despite your machine and LabVIEW being 64bit - the installed Java Runtime is only 32bit, which is actually not uncommon on Windows. Could you please try running both `java -d64 -version` and `java -d32 -version` on the command line (cmd.exe) to verify this? If my guess is correct, the first command will complain and the second one will output the 32bit Java version you have installed.

If this is the case, please download the x64/64bit JDK from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

If not, please let us also know so we can investigate further.

Thanks :)

**Comment by royerloic** [comment]
Ulrik is right, I checked the code, this is most likely the cause.
I would recommend first uninstalling the current Java version (if you don't need it) 
and the installing the latest Java version JDK8. Make sure that the JAVA _HOME
environment variable is correctly set:
https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/index.html
Let us know how it goes...

**Comment by cloudsforest** [comment]
Yes, you are correct. I installed the latest version of JDK8 and it is fine now. 

Thank you very much.

**Comment by royerloic** [comment]
I am curious, what are you going to use ClearVolume for?
I would like to collect a list of users, please feel free to write us a 
short description and when it works a screenshot, we can then add this
to a user cases wiki page and link back to your webpage if you wish so (we get quite some traffic).
 Let us know if that would be interesting to you :-)

**Comment by royerloic** [comment]
BTW, made the error message more explicit by adding a suggestion to install the latest Java version >=8
