### ISSUE TITLE
OpenCL volume rendering not working on OSX 10.11 with nVidia cards

### ISSUE THREAD

**Issue by skalarproduktraum** [ClearVolume/ClearVolume#36]
There seems to be a problem with how 3D textures are sampled in 10.11's nVidia driver. This causes `read_imagef` to only return zeroes, leading to a non-rendering of the volume. Investigating further...

Workaround for the moment: Run ClearVolume-based programs with `-DClearVolume.OpenCLDevice=0,1`, which selects the Iris Pro GPU on current MacBook Pros. It's usually fast enough for ClearVolume.

**Comment by skalarproduktraum** [comment]
After much testing, it turned out to actually be a driver bug.

Good news is, it already got fixed in 10.11.1! We should probably add a note to the README or something.

**Comment by royerloic** [comment]
The best would be to notify the user to upgrade to a more recent version

i) we detect the version
ii) if it is a problematic version, the we notify the user...
