### ISSUE TITLE
OpenCL renderer depends on CUDA through CudaException

### ISSUE THREAD

**Issue by skalarproduktraum** [ClearVolume/ClearVolume#37]
For some reason, in `OpenCLVolumeRenderer.renderVolume`, there's a try clause that checks for a `CudaException` (https://github.com/ClearVolume/ClearVolume/blob/master/src/java/clearvolume/renderer/opencl/OpenCLVolumeRenderer.java#L310) - was probably forgotten there for some reason.

**Comment by royerloic** [comment]
oups…
Yes, no good reason to be there… :-)

> On 25 Oct 2015, at 12:14, Ulrik Guenther <notifications@github.com> wrote:
> 
> For some reason, in OpenCLVolumeRenderer.renderVolume, there's a try clause that checks for a CudaException (https://github.com/ClearVolume/ClearVolume/blob/master/src/java/clearvolume/renderer/opencl/OpenCLVolumeRenderer.java#L310 <https://github.com/ClearVolume/ClearVolume/blob/master/src/java/clearvolume/renderer/opencl/OpenCLVolumeRenderer.java#L310>) - was probably forgotten there for some reason.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ClearVolume/ClearVolume/issues/37>.
> 

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by skalarproduktraum** [comment]
This is tentatively fixed with #50

**Comment by skalarproduktraum** [comment]
Fixed now.
