### ISSUE TITLE
The SPIM plugin download link is dead link

### ISSUE THREAD

**Issue by Ekulelu** [ClearVolume/ClearVolume#39]
I'm a SPIMer, and I'm just looking for a software to display the 3D-data. 
After seeing your video in your web site, I think this is what I looking for.
However, the download link for clearVolumw of SPIM plugin is a dead link. Can you fix this?
Or could you send me a plugin to my email 709314090@qq.com ? Thank you very much!

**Comment by skalarproduktraum** [comment]
Hey Ekulelu,

we'll fix the link, sorry for that.
Are you using Fiji? If yes, you can just enable the ClearVolume Update Site in the Updater window.

**Comment by royerloic** [comment]
@Ulrik: I think he might mean the OpenSPIM plugin…


> On 29 Oct 2015, at 14:05, Ulrik Guenther <notifications@github.com> wrote:
> 
> Hey Ekulelu,
> 
> we'll fix the link, sorry for that.
> Are you using Fiji? If yes, you can just enable the ClearVolume Update Site in the Updater window.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ClearVolume/ClearVolume/issues/39#issuecomment-152174031>.
> 

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/
